Output demo.gif

Set Shell "bash"
Set FontSize 13
Set Width 220
Set Height 50
Set Theme "Dracula"
Set Framerate 20

Type "grokfeed"
Enter
Sleep 10s

Down
Sleep 300ms
Down
Sleep 300ms
Down
Sleep 300ms
Down
Sleep 300ms
Down
Sleep 800ms

Enter
Sleep 1500ms
Down
Sleep 200ms
Down
Sleep 200ms
Down
Sleep 200ms
Type "q"
Sleep 800ms

Type "f"
Sleep 800ms
Type "f"
Sleep 800ms
Type "f"
Sleep 800ms

Type "q"
